# FROM node:14.15.4 AS compile-image

# RUN npm install -g yarn

# WORKDIR /opt/ng
# COPY .npmrc package.json yarn.lock ./
# RUN yarn install

# ENV PATH="./node_modules/.bin:$PATH" 

# COPY . ./
# RUN ng build --prod

# FROM nginx
# COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=compile-image /opt/ng/dist/app-name /usr/share/nginx/html

FROM node:14.15.4 AS compile-image
WORKDIR /app
COPY . .
RUN npm i && npm run build

FROM nginx
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=compile-image /app/dist/smartInitiatives .
ENTRYPOINT ["nginx", "-g", "daemon off;"]
