FROM node:alpine AS frontend

### STAGE 1: Build ###

# set working directory in the container i'm calling it app
WORKDIR /app
# copying the local code (evrything you see in the left) into /app
COPY . .
RUN npm install
RUN npm run build -- --prod
####Stage 2
FROM nginx
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=frontend /app/dist .
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

